// Zod source of truth for the final decision profile JSON.
// This is the JSON that lands in `perfil_decision_final.perfil_json` and feeds the
// future RAG. Generated by Opus extended-thinking 8K at session close (IMPLEMENTATION.md
// §10) from the full transcript + extracciones + casos sintéticos.
//
// Design:
//   - Output keyed by `caja_codigo` so RAG retrieval can target individual cajas.
//   - Each caja entry carries valor + confianza + fuente + evidencia, mirroring the
//     extraction row but collapsed to the latest non-superseded version per caja.
//   - `fuente` extends ExtraccionSchema's union with `decline_to_answer` and
//     `no_aplica` because those are valid post-cap states for cajas that never closed.
//   - `metricas.completitud` uses the per-session pinned denominator (sesiones.cajas_aplicables)
//     so v2 cajas don't change historical completitud values.

import { z } from 'zod';
import { TipoInstitucionSchema } from './casos';

// =============================================================================
// Per-caja entry
// =============================================================================
// Final-state fuente extends the extraction-time union: a caja might have closed via
// LLM, manual edit, OR neither (decline_to_answer when 5-case cap was hit before
// closing it; no_aplica when the entrevistado said "no aplica" explicitly, per §5.4).
export const FuenteCajaFinalSchema = z.enum([
  'llm',
  'manual',
  'decline_to_answer',
  'no_aplica',
]);
export type FuenteCajaFinal = z.infer<typeof FuenteCajaFinalSchema>;

// `valor` shape depends on caja — the type is intentionally `unknown` at this layer.
// Per-caja validation lives in `valorSchemaFor` (extracciones.ts). The synthesizer
// (Opus) is responsible for emitting the right shape; the Inngest job re-validates
// each entry against `valorSchemaFor(codigo)` before persisting.
export const CajaPerfilEntrySchema = z.object({
  valor: z.unknown(),
  confianza: z.number().min(0).max(1),
  fuente: FuenteCajaFinalSchema,
  evidencia_textual: z.string().nullable().optional(),
  // Number of LLM extractions issued for this caja before close. Useful telemetry —
  // a caja that needed 4 attempts is a prompt-quality signal.
  intentos: z.number().int().nonnegative().default(1),
});
export type CajaPerfilEntry = z.infer<typeof CajaPerfilEntrySchema>;

// =============================================================================
// Section metadata
// =============================================================================

export const InstitucionRefSchema = z.object({
  id: z.string().uuid(),
  razon_social: z.string().min(1),
  nombre_comercial: z.string().nullable(),
  tipo: TipoInstitucionSchema,
});

export const MetricasPerfilSchema = z.object({
  // Numerador / denominador del ratio completitud. Denominador es el snapshot pinned
  // en sesiones.cajas_aplicables — NO se recalcula con catálogos posteriores.
  cajas_llenas: z.number().int().nonnegative(),
  cajas_aplicables: z.number().int().positive(),
  completitud: z.number().min(0).max(1),
  confianza_global: z.number().min(0).max(1),
  // Ratios separados para críticas vs blandas — críticas son las que importan para
  // la decisión "fondea/no fondea"; blandas son contexto.
  cajas_criticas_pct: z.number().min(0).max(1),
  cajas_blandas_pct: z.number().min(0).max(1),
  // Cuántos casos sintéticos se mostraron (0..5 — cap global por sesión).
  casos_sinteticos_aplicados: z.number().int().min(0).max(5),
  fatiga_detectada: z.boolean(),
});
export type MetricasPerfil = z.infer<typeof MetricasPerfilSchema>;

// =============================================================================
// Top-level schema
// =============================================================================

export const PerfilDecisionFinalSchema = z.object({
  schema_version: z.literal('1.0'),
  institucion: InstitucionRefSchema,
  sesion_id: z.string().uuid(),
  generado_at: z.coerce.date(),
  metricas: MetricasPerfilSchema,
  // Mapa caja_codigo → entry. Incluye CANON + EXTENSION[tipo] aplicables a esta sesión.
  // Cajas no respondidas que cayeron al cap quedan con fuente = 'decline_to_answer'.
  cajas: z.record(z.string().min(1), CajaPerfilEntrySchema),
  // Resumen narrativo libre (1-3 párrafos) escrito por Opus en la síntesis. NO va al
  // RAG estructurado; sirve para la vista admin y como fallback humano.
  resumen_ejecutivo: z.string().min(1),
});
export type PerfilDecisionFinal = z.infer<typeof PerfilDecisionFinalSchema>;

// =============================================================================
// Cross-field invariants
// =============================================================================
// `metricas.completitud` debe coincidir con cajas_llenas / cajas_aplicables (±0.001
// para evitar falsos positivos por float). Lo enforza el writer; aquí lo validamos
// como red de seguridad antes de persistir.
export const PerfilDecisionFinalConsistenteSchema = PerfilDecisionFinalSchema.refine(
  (p) => {
    const ratio = p.metricas.cajas_llenas / p.metricas.cajas_aplicables;
    return Math.abs(ratio - p.metricas.completitud) < 0.001;
  },
  { message: 'metricas.completitud no coincide con cajas_llenas / cajas_aplicables', path: ['metricas', 'completitud'] }
).refine(
  (p) => p.metricas.cajas_llenas <= p.metricas.cajas_aplicables,
  { message: 'cajas_llenas no puede exceder cajas_aplicables', path: ['metricas', 'cajas_llenas'] }
);
